export { default as HomePage } from './HomePage'
export { default as ProductPage } from './ProductPage'
export { default as CartPage } from './CartPage'
export { default as CollectionsPage } from './CollectionsPage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'